### PR TITLE
story/RWA-1155 - Add support for `offset` param for services for getting pages

### PR DESCRIPTION
**Pull request by rotacloud-johnney**
This adds `offset` as an option so client can fetch specific pages from the endpoint.

### CODE REVIEW

**Review by liammoore4 — APPROVED** [review]

**Comment by richwatts0** [comment]
Do we need this when we have the auto paging methods and the fact you can get lists by page? Not opposed to putting this in just interested to know more context?

**Review by leonardrota — APPROVED** [review]

**Review by yujanrichie — APPROVED** [review]

**Comment by rotacloud-johnney** [comment]
@richwatts0 yup we do need it in the TOIL page since they want to put pagination in it but we don't have support for fetching specific pages currently.

**Comment by richwatts0** [comment]
> @richwatts0 yup we do need it in the TOIL page since they want to put pagination in it but we don't have support for fetching specific pages currently.

Why can't we use the paging mechanisms build into the SDK if we want paging on TOIL?

**Comment by rotacloud-johnney** [comment]
> > @richwatts0 yup we do need it in the TOIL page since they want to put pagination in it but we don't have support for fetching specific pages currently.
> 
> Why can't we use the paging mechanisms built into the SDK if we want paging on TOIL?

Not entirely sure how the paging mechanism in SDK works but I need to get a specific data from an specific offset with specific limit (they want it to be 50 by page). Also need a UI that is interactable to the user which would then emit the specific offset that would be fed to the SDK so it gets the proper page.

**Comment by liammoore4** [comment]
> > @richwatts0 yup we do need it in the TOIL page since they want to put pagination in it but we don't have support for fetching specific pages currently.
> 
> Why can't we use the paging mechanisms built into the SDK if we want paging on TOIL?

For context - the app currently has UI on certain routes for displaying a specific page:

Screenshot 2023-08-03 at 10 18 59

However before this change, I believe the only way we could do this would be to fetch every page in order up to the one you actually want.

**Pull request merged**
